apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "plano_de_corte_2026"
  # Você também pode colocar o HOST do banco aqui para o seu backend usar
  DATABASE_URL: "db" 