apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # O stringData permite colocar o valor em texto puro, 
  # o K8s converte para base64 automaticamente internamente.
  POSTGRES_PASSWORD: "postgres"
  # Adicione aqui outras chaves sensíveis se houver